using System;
using System.Collections.Generic;
using System.Text;

namespace Toolset.Net
{
  public enum Header
  {
    Accept,
    IfNoneMatch,
    IfRange,
    IfUnmodifiedSince,
    LastModified,
    Location,
    MaxForwards,
    Pragma,
    ProxyAuthenticate,
    ProxyAuthorization,
    Range,
    IfModifiedSince,
    Referer,
    Server,
    SetCookie,
    TE,
    Trailer,
    TransferEncoding,
    Upgrade,
    UserAgent,
    Vary,
    Via,
    Warning,
    RetryAfter,
    WebSocketSubProtocols,
    IfMatch,
    From,
    AcceptCharset,
    AcceptEncoding,
    AcceptLanguage,
    AcceptRanges,
    Age,
    Allow,
    Authorization,
    CacheControl,
    Connection,
    ContentDisposition,
    Host,
    ContentEncoding,
    ContentLength,
    ContentLocation,
    ContentMD5,
    ContentRange,
    ContentType,
    Cookie,
    Date,
    ETag,
    Expires,
    Expect,
    ContentLanguage,
    WWWAuthenticate
  }
}